### ISSUE TITLE
Comment installer PteroBilling ?

### ISSUE THREAD

**Issue by Nach37** [MinePlay85/PteroBilling-installer#1]
Bonjour,
Excuser moi de vous déranger mais j'ai vu que vous travailler sur l'installateur de PteroBilling et je souhaiterais l'installé. Seulement je voudrais savoir comment faire ? Je n'ai trouvé aucune informations sur internet. 

Cordialement, Nach37

**Comment by MinePlay85** [comment]
Bonsoir à toi !
Cette installer n'est pas encore disponible il est bientôt fini mais cela dois attendre 2-3j je metterais la commande d'installation quand celui-ci sera prêt.
Bonne soirée

**Comment by Nach37** [comment]
D'accord, merci pour votre réponse.
