### ISSUE TITLE
Command Not Found - PHP 8

### ISSUE THREAD

**Issue by ScoobyDooWaffle** [MinePlay85/PteroBilling-installer#5]
Hi , i get error command not found when it try to install PhP 8
![image](https://user-images.githubusercontent.com/76669896/125812361-21e61ec9-aecf-4443-92de-0842337406ad.png)

**Comment by MinePlay85** [comment]
Hi, I found the bug, I will resolve it now

**Comment by MinePlay85** [comment]
The bug is resolve. Can you re-test ?

**Comment by ScoobyDooWaffle** [comment]
Good , seems okay

**Comment by ScoobyDooWaffle** [comment]
E: The repository 'https://packages.sury.org/php bionic Release' does not have a                                Release file.
N: Updating from such a repository can't be done securely, and is therefore disa                               bled by default.
N: See apt-secure(8) manpage for repository creation and user configuration deta                               ils.

**Comment by MinePlay85** [comment]
Oh, this bug 😤

**Comment by MinePlay85** [comment]
Normally it should work
Best Regards.

**Comment by ScoobyDooWaffle** [comment]
What is best version of ubuntu are you using ?

**Comment by MinePlay85** [comment]
20.4

**Comment by ScoobyDooWaffle** [comment]
Is it required to have pterodactyl panel installed on same server ?

**Comment by MinePlay85** [comment]
No

**Comment by MinePlay85** [comment]
But PteroBilling-installer is based in Debian 10

**Comment by ScoobyDooWaffle** [comment]
I gonna try to install Debian 10 if is base on this

**Comment by ScoobyDooWaffle** [comment]
This is what i get on Debian 10 
![image](https://user-images.githubusercontent.com/76669896/125825181-a898c1eb-69f8-4b4d-a129-038f82d212ce.png)

**Comment by MinePlay85** [comment]
Bruh he don't install php

**Comment by ScoobyDooWaffle** [comment]
Oh lol ! , i forgot about this ahahah !sorry my bad omg !! 
It's nearly the weekend
